apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pihole
  name: pihole-config
  namespace: private-dns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: microk8s-hostpath
