apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default-addresspool
    metallb.universe.tf/allow-shared-ip: unbound-svc
  labels:
    app: unbound
  name: unbound-udp
  namespace: private-dns
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.50.4
  ports:
  - name: dns-udp
    port: 8053
    protocol: UDP
    targetPort: dns-udp
  selector:
    app: unbound
  sessionAffinity: None
  type: LoadBalancer
