apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: private-dns
  labels:
    app: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        image: udaikiran/unbound:0.0.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 8053
          protocol: TCP
          name: dns-tcp
        - containerPort: 8053
          protocol: UDP
          name: dns-udp
        livenessProbe:
          tcpSocket:
            port: 8053
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8053
          initialDelaySeconds: 5
          periodSeconds: 10